import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import DarkmodeProvider from "@/context/DarkmodeProvider";

const OpenSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DarkmodeProvider>
        <body
          className={`${"bg-slate-200 dark:bg-slate-800"} + ${
            OpenSans.className
          }`}
        >
          <header>
            <Header />
          </header>
          <main>{children}</main>
        </body>
      </DarkmodeProvider>
    </html>
  );
}
