import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import DarkmodeProvider from "@/context/DarkmodeProvider";
import AuthProvider from "@/context/AuthProvider";

const OpenSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${"bg-slate-200 dark:bg-slate-800 w-full max-w-screen-lg overflow-auto mx-auto"} + ${
          OpenSans.className
        }`}
      >
        <DarkmodeProvider>
          <AuthProvider>
            <header className="sticky top-0 bg-blue-200 dark:bg-slate-700 z-10 border-b border-white dark:border-gray-400">
              <Header />
            </header>
            <main>{children}</main>
          </AuthProvider>
        </DarkmodeProvider>
      </body>
    </html>
  );
}
